language: swift
osx_image: xcode12.0

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    
addons:
  ssh_known_hosts: github.com

notifications:
  email: false
  
before_install:
  - env
  - locale
  - gem install cocoapods --no-document --quiet
  - gem install xcpretty --no-document --quiet
  - pod --version
  - pod repo update --silent
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  
  - set -o pipefail

  - echo Check if the library described by the podspec can be built
  - pod lib lint --allow-warnings

  - echo Build iPadSplitScreenDemo
  - pod install
  - xcodebuild build -workspace iPadSplitScreenDemo.xcworkspace -scheme iPadSplitScreenDemo -destination 'platform=iOS Simulator,name=iPhone X' -configuration Debug | xcpretty -c


  - echo Clean DerivedData
  - rm -rf ~/Library/Developer/Xcode/DerivedData/
  - mkdir DerivedData

